dependencies:
    "ansible.netcommon": "*"
description: ''
documentation: ''
homepage: ''
issues: ''
license: "Apache-2.0"
name: aos_switch
namespace: arubanetworks
readme: README.md
repository: ''
tags: [
  networking,
  aruba,
  switch,
  switches,
  hpe,
  datacenter
]
version: 1.2.0
authors:
  - "Tiffany Chiapuzio-Wong"
  - "Sunil Veeramachaneni"
  - "Castro, Jorge Arturo"
